const Prop = {
    TITLE: "Architech",
    API_END_POINT: process.env.REACT_APP_API_ENDPOINT,
    TIME_OUT: 1000,
    RESEND_MAIL_TIME: 30,
    MAX_WIDTH: "1400px",
    EMAIL_PATTERN: "[A-Z0-9a-z._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,64}",
    PASSWORD_PATTERN: /^(?=.*[a-z])(?=.*[A-Z])(?=.*d)(?=.*[@$!%*?&#])[#A-Za-zd@$!%*?&]{8,12}$/,
    // "^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[@$!%*?&])[A-Za-z\\d@$!%*?&]{8,}$",
    ALL_PATTERN: "(.*?)",
    DATA_PATTERN: "^[^\\s]+[\\w\\d\\s.,&@:;!#-=\u0600-\u06FF]*$",
    //  DATA_PATTERN:"[\\w\\d\\s.,&@:;!#-=\u0600-\u06FF]*$",
    DATA_PATTERN_ARABIC: "~^[a-z0-9٠-٩-+,()/'sp{Arabic}]{1,60}$~iu",
    DECIMAL_PATTERN: "(\\d+(\\.\\d{1,2})?)",
    DECIMAL_PATTERN_SIXDIGITS: "(\\d+(\\.\\d{1,6})?)",
    NUMBER_PATTERN: "[0-9]*",
    MONTHS_PATTERN: "^([1-9]|1[012])$",
    PHONE_PATTERN: "^[6-9][0-9]{9}$",
    PHONE_PATTERN_NEW: "^[1-9][0-9]{9}$",
    AADHAR_PATTERN: "^[0-9]{12}$",
    ZIPCODE_PATTERN: "^[5][0-9]{5}$",
    COLOR_PATTERN: "(^#[0-9A-F]{6}$)|(^#[0-9A-F]{3}$)",
    LONGITUDE_PATTERN: "^[-+]?([1-8]?d(.d+)?|90(.0+)?),s*[-+]?(180(.0+)?|((1[0-7]d)|([1-9]?d))(.d+)?)$",

    // DATE_PATTERN:'(?:19|20)[0-9]{2}-(?:(?:0[1-9]|1[0-2])-(?:0[1-9]|1[0-9]|2[0-9])|(T?:(?!02)(?:0[1-9]|1[0-2])-(?:30))|(?:(?:0[13578]|1[02])-31))',
    DATE_PATTERN: "[\\w\\d\\s.,&@:;!#-=]*",
    APLPHA_NUMERIC_PATTERN: "^[a-zA-Z0-9_]*$",
    APLPHA_NUMERICS_PATTERN: "^[a-zA-Z0-9]*$",
    ALPHABETICAL_PATTERN: "^[a-zA-Z\\-\\s \u0600-\u06FF]*$",
    ALPHABETICALS_PATTERN: "^[a-zA-Z\\-\\s \u0600-\u06FF]*$",
    LOCATION_PATTERN: "[a-zA-Z0-9 ]*$",
    APLPHA_PATTERN: "[a-zA-Z ]*$",
    FULLNAME_PATTERN: "^([A-z][A-Za-z]*s+[A-Za-z]*)|([A-z][A-Za-z]*)$",
    ARABICNAME_PATTERN: "^([^ ])|(\\w\\d\\s.,&@:;!#-=)",
    AMT_PATTERN: "^[0-9]*$",
    DISCOUNT_PATTERN: "^\\d{0,2}(\\.\\d{1,2})?$",
};

export default Prop;
